### ISSUE TITLE
Mentions for models without a `slug` field

### ISSUE THREAD

**Issue by campegg** [beatonma/django-wm#40]
More of a question than an issue: I have a couple of legacy models that do not have a `slug` field, and am wondering if it is possible to enable mentions for them. I have tried defining a `slug` in the model:

```
@property
def slug(self):
    return self.id
```

… but it doesn't seem to work; I get:

```
File "[_PATH TO DJANGO..._]/venv/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1709, in names_to_path
    raise FieldError(
        django.core.exceptions.FieldError: Cannot resolve keyword 'slug' into field. Choices are: [_MODEL FIELD NAMES..._]
    )
```

Is there a way I can work around this?

**Comment by beatonma** [comment]
Hey,

For now you should be able to set `slug = None` on your model to [prevent inheriting](https://docs.djangoproject.com/en/4.1/topics/db/models/#field-name-hiding-is-not-permitted) it from `MentionableMixin`. You will also need to override the `resolve_from_url_kwargs` classmethod.

e.g.

```python
# models.py
class Article(MentionableMixin, models.Model):
    title = models.CharField(max_length=64)
    content = models.TextField()

    slug = None

    def all_text(self) -> str:
        return self.content

    def get_absolute_url(self) -> str:
        return reverse("article", args=[self.pk])

    @classmethod
    def resolve_from_url_kwargs(cls, article_id: int, **url_kwargs) -> "Article":
        return Article.objects.get(pk=article_id)


# urls.py
urlpatterns = [
    path(
        "article/<int:article_id>/",
        ArticleView.as_view(),
        name="article",
        kwargs={
            "model_name": "sample_app.Article",
        },
    ),
]
```


The slug field will likely be removed from `MentionableMixin` in the next major release as it is no longer required (since `2.3.0`) and only used to provide the default `resolve_from_url_kwargs` implementation.

**Comment by campegg** [comment]
Thanks @beatonma — much appreciated!
